-- Migration 012: Upsert completo da lista de bases operacionais GOLLOG
-- Fonte: planilha de E-mails Operacionais (jun/2026)

CREATE TABLE IF NOT EXISTS bases_email (
  id        BIGSERIAL PRIMARY KEY,
  sigla     TEXT UNIQUE NOT NULL,
  nome      TEXT,
  email     TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO bases_email (sigla, nome, email) VALUES
  ('AJU', 'Aracaju',                          'gr-ajufk@voegol.com.br'),
  ('ARU', 'Araçatuba',                         'arufk@voegol.com.br'),
  ('BAU', 'Bauru',                             'baufk@voegol.com.br'),
  ('BEL', 'Belém',                             'belfk@voegol.com.br'),
  ('BGV', 'Bento Gonçalves',                   'bgvfk@voegol.com.br'),
  ('BNU', 'Blumenau',                          'bnufk@voegol.com.br'),
  ('BPS', 'Porto Seguro',                      'bpsfk@voegol.com.br'),
  ('BSB', 'Brasilia',                          'bsbfk@voegol.com.br'),
  ('BVB', 'Boa Vista',                         'bvbfk@voegol.com.br'),
  ('CAC', 'Cascavel',                          'cacfk@voegol.com.br'),
  ('CAU', 'Caruaru',                           'caufk@voegol.com.br'),
  ('CCM', 'Criciúma',                          'ccmfk@voegol.com.br'),
  ('CGB', 'Cuiabá - Varzea Grande',            'cgbfk@voegol.com.br'),
  ('CGH', 'São Paulo (Congonhas)',              'cghfk@voegol.com.br'),
  ('CGL', 'Campo Grande',                      'cglfk@voegol.com.br'),
  ('CGR', 'Campo Grande',                      'cgrfk@voegol.com.br'),
  ('CGU', 'São Paulo',                         'cgufk@voegol.com.br'),
  ('CKS', 'Parauapebas',                       'cksfk@voegol.com.br'),
  ('CNF', 'Confins - Lagoa Santa',             'cnffk@voegol.com.br'),
  ('CPV', 'Campina Grande',                    'cpvfk@voegol.com.br'),
  ('CWB', 'Curitiba - São José Dos Pinhais',   'cwbfk@voegol.com.br'),
  ('CXJ', 'Caxias Do Sul',                     'cxjfk@voegol.com.br'),
  ('CZS', 'Cruzeiro Do Sul',                   'czsfk@voegol.com.br'),
  ('DFV', 'Brasilia',                          'dfvfk@voegol.com.br'),
  ('ETX', 'Extrema',                           'etxfk@voegol.com.br'),
  ('FEN', 'Fernando de Noronha',               'fenfk@voegol.com.br'),
  ('FFR', 'Franca',                            'ffrfk@voegol.com.br'),
  ('FLN', 'Florianópolis',                     'flnfk@voegol.com.br'),
  ('FOR', 'Fortaleza',                         'forfk@voegol.com.br'),
  ('FTZ', 'Fortaleza',                         'ftzfk@voegol.com.br'),
  ('GIG', 'Rio De Janeiro',                    'gigfk@voegol.com.br'),
  ('GOD', 'Goiânia - Centro Oeste',            'godfk@voegol.com.br'),
  ('GOI', 'Goiânia - Setor Ferroviário',       'goifk@voegol.com.br'),
  -- GRU tem e-mail secundário gr-colaboradoresgrufk@voegol.com.br (adicionar em CC manualmente se necessário)
  ('GRU', 'Guarulhos',                         'grufk@voegol.com.br'),
  ('GYN', 'Goiânia - Aeroporto',               'gynfk@voegol.com.br'),
  ('IGU', 'Foz Do Iguaçu',                     'igufk@voegol.com.br'),
  ('IOS', 'Ilheus',                            'iosfk@voegol.com.br'),
  ('JDF', 'Juiz De Fora',                      'jdffk@voegol.com.br'),
  ('JDO', 'Juazeiro Do Norte',                 'jdofk@voegol.com.br'),
  ('JJD', 'Jericocara - Cruz',                 'jjdfk@voegol.com.br'),
  ('JOI', 'Joinville',                         'joifk@voegol.com.br'),
  ('JPA', 'João Pessoa - Bayeux',              'jpafk@voegol.com.br'),
  ('LDB', 'Londrina',                          'ldbfk@voegol.com.br'),
  ('MAB', 'Maraba',                            'mabfk@voegol.com.br'),
  ('MAO', 'Manaus',                            'maofk@voegol.com.br'),
  ('MCP', 'Macapá',                            'mcpfk@voegol.com.br'),
  ('MCZ', 'Rio Largo',                         'mczfk@voegol.com.br'),
  ('MGF', 'Maringa',                           'mgffk@voegol.com.br'),
  ('MII', 'Marilia',                           'miifk@voegol.com.br'),
  ('MOC', 'Montes Claros',                     'mocfk@voegol.com.br'),
  ('NAT', 'Natal - São Gonçalo Do Amarante',   'natfk@voegol.com.br'),
  ('NSA', 'Nova Serrana',                      'nsafk@voegol.com.br'),
  ('NVT', 'Navegantes',                        'nvtfk@voegol.com.br'),
  ('OPS', 'Sinop',                             'opsfk@voegol.com.br'),
  ('PET', 'Pelotas',                           'petfk@voegol.com.br'),
  ('PFB', 'Passo Fundo',                       'pfbfk@voegol.com.br'),
  ('PLU', 'Belo Horizonte',                    'plufk@voegol.com.br'),
  ('PMW', 'Palmas',                            'pmwfk@voegol.com.br'),
  ('PNZ', 'Petrolina',                         'pnzfk@voegol.com.br'),
  ('POA', 'Porto Alegre',                      'poafk@voegol.com.br'),
  ('PPB', 'Presidente Prudente',               'ppfk@voegol.com.br'),
  ('PTS', 'Petrópolis',                        'ptsfk@voegol.com.br'),
  ('PVH', 'Porto Velho',                       'pvhfk@voegol.com.br'),
  ('QAT', 'Atibaia',                           'qatfk@voegol.com.br'),
  ('QBA', 'Salvador',                          'qbafk@voegol.com.br'),
  ('QBQ', 'Brusque',                           'qbqfk@voegol.com.br'),
  ('QBR', 'São Paulo',                         'qbrfk@voegol.com.br'),
  ('QBX', 'Barueri',                           'qbxfk@voegol.com.br'),
  ('QCC', 'Santa Cruz do Capibaribe',          'qccfk@voegol.com.br'),

  ('QCS', 'São Caetano do Sul',                'qcsfk@voegol.com.br'),
  ('QDI', 'Uberlândia',                        'qdifk@voegol.com.br'),
  ('QDM', 'Diadema',                           'qdmfk@voegol.com.br'),
  ('QDV', 'Jundiai',                           'qdvfk@voegol.com.br'),
  ('QFS', 'Feira de Santana',                  'qfsfk@voegol.com.br'),
  ('QGL', 'São Paulo (Vila Carrão)',            'qglfk@voegol.com.br'),
  ('QHV', 'Novo Hamburgo',                     'qhvfk@voegol.com.br'),
  ('QIP', 'São Paulo (Ipiranga)',               'qipfk@voegol.com.br'),
  ('QLI', 'Limeira',                           'qlifk@voegol.com.br'),
  ('QMA', 'Manaus',                            'qmafk@voegol.com.br'),
  ('QMI', 'Mogi Das Cruzes',                   'qmifk@voegol.com.br'),
  ('QNL', 'Natal',                             'qnlfk@voegol.com.br'),
  ('QNR', 'Niterói',                           'qnrfk@voegol.com.br'),
  ('QNT', 'Contagem',                          'qntfk@voegol.com.br'),
  ('QOT', 'Cotia',                             'qotfk@voegol.com.br'),
  ('QOZ', 'Osasco',                            'qozfk@voegol.com.br'),
  ('QPR', 'Piracicaba',                        'qprfk@voegol.com.br'),
  ('QRS', 'Pouso Alegre',                      'qrsfk@voegol.com.br'),
  ('QSB', 'Sobral',                            'qsbfk@voegol.com.br'),
  ('QSE', 'Santo André',                       'qsefk@voegol.com.br'),
  ('QSP', 'São Paulo (Berrini)',               'qspfk@voegol.com.br'),
  ('QTB', 'Taubaté',                           'qtbfk@voegol.com.br'),
  ('QVL', 'Valinhos',                          'qvlfk@voegol.com.br'),
  ('RAO', 'Ribeirão Preto',                    'raofk@voegol.com.br'),
  ('RBR', 'Rio Branco',                        'rbrfk@voegol.com.br'),
  ('REC', 'Recife',                            'recfk@voegol.com.br'),
  ('RJV', 'Rio De Janeiro',                    'rjvfk@voegol.com.br'),
  ('RSF', 'Porto Alegre',                      'rsffk@voegol.com.br'),
  ('SBC', 'São Bernando do Campo',             'sbcfk@voegol.com.br'),
  ('SDU', 'Rio De Janeiro',                    'sdufk@voegol.com.br'),
  ('SJK', 'São Jose Dos Campos',               'sjkfk@voegol.com.br'),
  ('SJP', 'São Jose Do Rio Preto',             'sjpfk@voegol.com.br'),
  ('SLZ', 'São Luis',                          'slzfk@voegol.com.br'),
  ('SOD', 'Sorocaba',                          'sodfk@voegol.com.br'),
  ('SPA', 'São Paulo (Republica)',              'spafk@voegol.com.br'),
  ('SPG', 'São Paulo (Zona Leste)',             'spgfk@voegol.com.br'),
  ('SPM', 'São Paulo (Vila Maria)',             'spmfk@voegol.com.br'),
  ('SPO', 'São Paulo (Vila Leopoldina)',        'spofk@voegol.com.br'),
  ('SPX', 'Guarulhos',                         'spxfk@voegol.com.br'),
  ('SSA', 'Salvador',                          'ssafk@voegol.com.br'),
  ('SSZ', 'Santos',                            'sszfk@voegol.com.br'),
  ('STM', 'Santarém',                          'stmfk@voegol.com.br'),
  ('THE', 'Teresina',                          'thefk@voegol.com.br'),
  ('UDI', 'Uberlândia',                        'udifk@voegol.com.br'),
  ('VAG', 'Varginha',                          'vagfk@voegol.com.br'),
  ('VCP', 'Campinas',                          'vcpfk@voegol.com.br'),
  ('VDC', 'Vitória da Conquista',              'vdcfk@voegol.com.br'),
  ('VGL', 'São Paulo (Campos Elíseos)',         'vglfk@voegol.com.br'),
  ('VIX', 'Vitória',                           'vixfk@voegol.com.br'),
  ('VJD', 'São Paulo (Santo Amaro)',            'vjdfk@voegol.com.br'),
  ('VNH', 'Vinhedo',                           'vnhfk@voegol.com.br'),
  ('XAP', 'Chapecó',                           'xapfk@voegol.com.br')
ON CONFLICT (sigla) DO UPDATE SET
  nome  = EXCLUDED.nome,
  email = EXCLUDED.email;
